service: barksh-module-authentication
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./typescript/tsconfig.build.json"

functions:
  api:
    handler: src/handlers/create-account.createAccountHandler
    events:
      - httpApi:
          path: /account/create
          method: post
