service: barksh-module-authentication
frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource:
        - "*"
  region: us-east-1
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  apiGateway:
    minimumCompressionSize: 1024

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./typescript/tsconfig.build.json"
  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

functions:
  CreateAccount:
    handler: src/handlers/account/create.createAccountHandler
    environment:
      APIG_DEPLOYMENT_ID: TestTest
    events:
      - httpApi:
          path: /account/create
          method: post
