service: barksh-module-authentication
frameworkVersion: "3"

provider: ${file(./config/provider-aws.yml)}

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./typescript/tsconfig.build.json"
  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

functions:
  CreateAccount:
    handler: src/handlers/v1/account/create.createAccountHandler
    events:
      - httpApi:
          path: /v1/account/create
          method: post
