service: barksh-module-authentication
frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  iamRoleStatements: ${file(config/iam-role-statements.json)}
  region: us-east-1
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    ROOT_DYNAMO_DB_ARN: ${env:ROOT_DYNAMO_DB_ARN}

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./typescript/tsconfig.build.json"
  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

functions:
  CreateAccount:
    handler: src/handlers/account/create.createAccountHandler
    events:
      - httpApi:
          path: /account/create
          method: post
