name: aws
stage: prod
region: us-east-1
runtime: nodejs18.x
memorySize: 256
timeout: 10
apiGateway:
  minimumCompressionSize: 1024
environment:
  AUTHENTICATION_MONGO_DB: ${env:AUTHENTICATION_MONGO_DB}
